# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ab66a1706bab73811db331898765ea60b156de69ba66239ae3ece7b62d2b2be0849e8876b3a7371a4f80f4f40a4fb7656ec54a29935647a0f3d4a4ff3331395

test:
  secret_key_base: 9a778be1455128a880d07f7863e499bca4110f134e4731743ac628a12390d2441116dcff937f19ea57b1b85d9f6c49da2b834131e73e6eebf78d3757842ae694

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
